// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reconnect.Modules.Safety.Infrastructure;

#nullable disable

namespace Reconnect.Modules.Safety.Infrastructure.Migrations
{
    [DbContext(typeof(SafetyDbContext))]
    [Migration("20260926092212_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("safety")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reconnect.Modules.Safety.Domain.Block", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BlockedId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocked_id");

                    b.Property<Guid>("BlockerId")
                        .HasColumnType("uuid")
                        .HasColumnName("blocker_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("Id")
                        .HasName("pk_blocks");

                    b.HasIndex("BlockedId")
                        .HasDatabaseName("ix_blocks_blocked_id");

                    b.HasIndex("BlockerId", "BlockedId")
                        .IsUnique()
                        .HasDatabaseName("ix_blocks_blocker_id_blocked_id");

                    b.ToTable("blocks", "safety");
                });

            modelBuilder.Entity("Reconnect.Modules.Safety.Domain.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReportedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_user_id");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("ReportedUserId")
                        .HasDatabaseName("ix_reports_reported_user_id");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_reports_status_created_at");

                    b.ToTable("reports", "safety");
                });
#pragma warning restore 612, 618
        }
    }
}
