// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reconnect.Modules.City.Infrastructure;

#nullable disable

namespace Reconnect.Modules.City.Infrastructure.Migrations
{
    [DbContext(typeof(CityDbContext))]
    [Migration("20260926180050_SeebadUtoquai")]
    partial class SeebadUtoquai
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("city")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reconnect.Modules.City.Domain.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("address");

                    b.Property<Polygon>("Footprint")
                        .HasColumnType("geography (polygon, 4326)")
                        .HasColumnName("footprint");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_buildings");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_buildings_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("buildings", "city");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000001"),
                            Address = "Bahnhofplatz 1, 8001 Zürich",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (8.54018 47.37785)"),
                            Name = "Zürich HB"
                        },
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000002"),
                            Address = "Grossmünsterplatz, 8001 Zürich",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (8.54411 47.37011)"),
                            Name = "Grossmünster"
                        },
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000003"),
                            Address = "Hardstrasse 201, 8005 Zürich",
                            Footprint = (NetTopologySuite.Geometries.Polygon)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POLYGON ((8.5172916 47.3858168, 8.5173161 47.3858427, 8.5174734 47.3859997, 8.5174691 47.3860325, 8.5174531 47.3861503, 8.5174915 47.3862611, 8.5175038 47.3862929, 8.5172469 47.3864032, 8.5172227 47.3863787, 8.5170682 47.3862219, 8.517071 47.3861908, 8.5170859 47.3860271, 8.5170304 47.3859049, 8.5170173 47.3858759, 8.5172916 47.3858168))"),
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (8.51733 47.38622)"),
                            Name = "Prime Tower"
                        },
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000004"),
                            Address = "Rämistrasse 101, 8092 Zürich",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (8.54798 47.37635)"),
                            Name = "ETH Hauptgebäude"
                        },
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000005"),
                            Address = "Falkenstrasse 1, 8008 Zürich",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (8.54671 47.3649)"),
                            Name = "Opernhaus Zürich"
                        },
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000006"),
                            Address = "Museumstrasse 2, 8001 Zürich",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (8.54063 47.37926)"),
                            Name = "Landesmuseum"
                        },
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000007"),
                            Address = "Heimplatz 1, 8001 Zürich",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (8.54826 47.37036)"),
                            Name = "Kunsthaus Zürich"
                        },
                        new
                        {
                            Id = new Guid("0199a000-0000-7000-8000-000000000008"),
                            Address = "Utoquai 49, 8008 Zürich",
                            Location = (NetTopologySuite.Geometries.Point)new NetTopologySuite.IO.WKTReader().Read("SRID=4326;POINT (8.54895 47.36271)"),
                            Name = "Seebad Utoquai"
                        });
                });

            modelBuilder.Entity("Reconnect.Modules.City.Domain.MapUsage", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date")
                        .HasColumnName("month");

                    b.Property<int>("GoogleSessions")
                        .HasColumnType("integer")
                        .HasColumnName("google_sessions");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean")
                        .HasColumnName("is_premium");

                    b.HasKey("UserId", "Month")
                        .HasName("pk_map_usage");

                    b.HasIndex("Month", "IsPremium")
                        .HasDatabaseName("ix_map_usage_month_is_premium");

                    b.ToTable("map_usage", "city");
                });
#pragma warning restore 612, 618
        }
    }
}
