// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Reconnect.Modules.Rooms.Infrastructure;

#nullable disable

namespace Reconnect.Modules.Rooms.Infrastructure.Migrations
{
    [DbContext(typeof(RoomsDbContext))]
    partial class RoomsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("rooms")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Reconnect.Modules.Rooms.Domain.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Depth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("depth");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("cozy")
                        .HasColumnName("theme");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Width")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("width");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_rooms_owner_id");

                    b.HasIndex("BuildingId", "IsPublic")
                        .HasDatabaseName("ix_rooms_building_id_is_public");

                    b.ToTable("rooms", "rooms");
                });

            modelBuilder.Entity("Reconnect.Modules.Rooms.Domain.Room", b =>
                {
                    b.OwnsMany("Reconnect.Modules.Rooms.Domain.RoomItem", "Layout", b1 =>
                        {
                            b1.Property<Guid>("RoomId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("ItemId")
                                .IsRequired();

                            b1.Property<float>("Rotation");

                            b1.HasKey("RoomId", "__synthesizedOrdinal");

                            b1.ToTable("rooms", "rooms");

                            b1
                                .ToJson("layout")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("RoomId")
                                .HasConstraintName("fk_rooms_rooms_room_id");

                            b1.OwnsOne("Reconnect.Modules.Rooms.Domain.Position3", "Position", b2 =>
                                {
                                    b2.Property<Guid>("RoomItemRoomId");

                                    b2.Property<int>("RoomItem__synthesizedOrdinal");

                                    b2.Property<float>("X");

                                    b2.Property<float>("Y");

                                    b2.Property<float>("Z");

                                    b2.HasKey("RoomItemRoomId", "RoomItem__synthesizedOrdinal")
                                        .HasName("pk_rooms");

                                    b2.ToTable("rooms", "rooms");

                                    b2.WithOwner()
                                        .HasForeignKey("RoomItemRoomId", "RoomItem__synthesizedOrdinal")
                                        .HasConstraintName("fk_rooms_rooms_room_item_room_id_room_item__synthesized_ordinal");
                                });

                            b1.Navigation("Position")
                                .IsRequired();
                        });

                    b.Navigation("Layout");
                });
#pragma warning restore 612, 618
        }
    }
}
