<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Reconnect.SharedKernel\Reconnect.SharedKernel.csproj" />
    <ProjectReference Include="..\Modules\Identity\Reconnect.Modules.Identity\Reconnect.Modules.Identity.csproj" />
    <ProjectReference Include="..\Modules\Profiles\Reconnect.Modules.Profiles\Reconnect.Modules.Profiles.csproj" />
    <ProjectReference Include="..\Modules\Safety\Reconnect.Modules.Safety\Reconnect.Modules.Safety.csproj" />
    <ProjectReference Include="..\Modules\Social\Reconnect.Modules.Social\Reconnect.Modules.Social.csproj" />
    <ProjectReference Include="..\Modules\City\Reconnect.Modules.City\Reconnect.Modules.City.csproj" />
    <ProjectReference Include="..\Modules\Rooms\Reconnect.Modules.Rooms\Reconnect.Modules.Rooms.csproj" />
    <ProjectReference Include="..\Modules\Wallet\Reconnect.Modules.Wallet\Reconnect.Modules.Wallet.csproj" />
    <ProjectReference Include="..\Modules\RealEstate\Reconnect.Modules.RealEstate\Reconnect.Modules.RealEstate.csproj" />
    <ProjectReference Include="..\Reconnect.Contracts\Reconnect.Contracts.csproj" />
    <ProjectReference Include="..\Reconnect.ServiceDefaults\Reconnect.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Storage.Blobs" />
    <PackageReference Include="Aspire.StackExchange.Redis" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

</Project>
