using System.Reflection;
using NetArchTest.Rules;
using Reconnect.Modules.City;
using Reconnect.Modules.Identity;
using Reconnect.Modules.Profiles;
using Reconnect.Modules.RealEstate;
using Reconnect.Modules.Rooms;
using Reconnect.Modules.Safety;
using Reconnect.Modules.Social;
using Reconnect.Modules.Wallet;
using Reconnect.SharedKernel.Modules;

namespace Reconnect.ArchitectureTests;

/// <summary>
/// Guards the modular monolith: modules only know the modules they are allowed to know, and even
/// then only their <c>Public</c> namespace. Change <see cref="AllowedDependencies"/> consciously –
/// a new arrow here is an architecture decision (and must never create a cycle).
/// </summary>
public sealed class ModuleBoundaryTests
{
    private static readonly Dictionary<string, Assembly> Modules = new()
    {
        ["Identity"] = typeof(IdentityModule).Assembly,
        ["Profiles"] = typeof(ProfilesModule).Assembly,
        ["Safety"] = typeof(SafetyModule).Assembly,
        ["Social"] = typeof(SocialModule).Assembly,
        ["City"] = typeof(CityModule).Assembly,
        ["Rooms"] = typeof(RoomsModule).Assembly,
        ["Wallet"] = typeof(WalletModule).Assembly,
        ["RealEstate"] = typeof(RealEstateModule).Assembly,
    };

    private static readonly Dictionary<string, string[]> AllowedDependencies = new()
    {
        ["Identity"] = [],
        ["City"] = [],
        ["Safety"] = ["Identity"],
        ["Profiles"] = ["Identity", "Safety"],
        ["Social"] = ["Profiles", "Safety"],
        ["Rooms"] = ["Identity", "Profiles", "Safety", "City"],
        ["Wallet"] = [],
        ["RealEstate"] = ["Wallet", "Rooms", "City"],
    };

    public static TheoryData<string> ModuleNames => [.. Modules.Keys];

    [Theory]
    [MemberData(nameof(ModuleNames))]
    public void Module_references_only_allowed_modules(string module)
    {
        var referenced = Modules[module].GetReferencedAssemblies()
            .Select(a => a.Name!)
            .Where(n => n.StartsWith("Reconnect.Modules.", StringComparison.Ordinal))
            .Select(n => n["Reconnect.Modules.".Length..])
            .ToList();

        Assert.All(referenced, r => Assert.Contains(r, AllowedDependencies[module]));
    }

    [Theory]
    [MemberData(nameof(ModuleNames))]
    public void Module_uses_other_modules_only_through_their_public_namespace(string module)
    {
        var forbidden = Modules.Keys
            .Where(other => other != module)
            .SelectMany(other => new[]
            {
                $"Reconnect.Modules.{other}.Domain",
                $"Reconnect.Modules.{other}.Features",
                $"Reconnect.Modules.{other}.Infrastructure",
                $"Reconnect.Modules.{other}.Hubs",
                $"Reconnect.Modules.{other}.{other}Module",
            })
            .ToArray();

        var result = Types.InAssembly(Modules[module]).ShouldNot().HaveDependencyOnAny(forbidden).GetResult();

        Assert.True(result.IsSuccessful, Failing(result));
    }

    [Fact]
    public void Dependency_graph_has_no_cycles()
    {
        var visiting = new HashSet<string>();
        var done = new HashSet<string>();

        void Visit(string module, Stack<string> path)
        {
            if (done.Contains(module))
            {
                return;
            }
            path.Push(module);
            Assert.True(visiting.Add(module), $"Cycle: {string.Join(" -> ", path.Reverse())}");
            foreach (var dependency in AllowedDependencies[module])
            {
                Visit(dependency, path);
            }
            visiting.Remove(module);
            done.Add(module);
            path.Pop();
        }

        foreach (var module in Modules.Keys)
        {
            Visit(module, new Stack<string>());
        }
    }

    [Theory]
    [MemberData(nameof(ModuleNames))]
    public void Public_surface_is_the_module_class_the_public_namespace_and_hub_client_interfaces(string module)
    {
        var root = $"Reconnect.Modules.{module}";
        var unexpected = Modules[module].GetExportedTypes()
            .Where(t => !(t.Namespace == root && typeof(IModule).IsAssignableFrom(t)))
            .Where(t => t.Namespace != $"{root}.Public")
            .Where(t => !(t.Namespace == $"{root}.Hubs" && t.IsInterface))
            .Where(t => t.Namespace != $"{root}.Infrastructure.Migrations")   // generated by EF
            .Select(t => t.FullName)
            .ToList();

        Assert.True(unexpected.Count == 0, "Unexpected public types: " + string.Join(", ", unexpected));
    }

    [Theory]
    [MemberData(nameof(ModuleNames))]
    public void Domain_does_not_depend_on_persistence_or_web(string module)
    {
        var result = Types.InAssembly(Modules[module])
            .That().ResideInNamespace($"Reconnect.Modules.{module}.Domain")
            .ShouldNot().HaveDependencyOnAny(
                "Microsoft.EntityFrameworkCore", "Microsoft.AspNetCore", "Npgsql", "StackExchange.Redis",
                $"Reconnect.Modules.{module}.Infrastructure", $"Reconnect.Modules.{module}.Features")
            .GetResult();

        Assert.True(result.IsSuccessful, Failing(result));
    }

    [Theory]
    [MemberData(nameof(ModuleNames))]
    public void Every_module_has_exactly_one_module_class(string module)
    {
        var moduleTypes = Modules[module].GetTypes()
            .Where(t => typeof(IModule).IsAssignableFrom(t) && !t.IsAbstract)
            .ToList();

        var single = Assert.Single(moduleTypes);
        Assert.Equal($"Reconnect.Modules.{module}.{module}Module", single.FullName);
    }

    private static string Failing(TestResult result) =>
        "Violations: " + string.Join(", ", result.FailingTypeNames ?? []);
}
