using System;
using System.Collections.Generic;
using UnityEngine;

namespace Reconnect.Client.Rooms
{
    /// <summary>
    /// Maps the ItemId stored in a room layout to a 3D model. Generated by ProjectSetup from
    /// Assets/ThirdParty/Kenney/Furniture (ItemId = file name, e.g. "loungeSofa").
    /// Asset: Assets/_Project/Settings/ItemCatalog.asset.
    /// </summary>
    [CreateAssetMenu(menuName = "Reconnect/Item Catalog", fileName = "ItemCatalog")]
    public sealed class ItemCatalog : ScriptableObject
    {
        [Serializable]
        public sealed class Entry
        {
            public string itemId;
            public GameObject model;
        }

        [Tooltip("Kenney furniture uses 10 units per floor tile; our tiles are 1 m.")]
        public float modelScale = 0.1f;
        public List<Entry> items = new();

        private Dictionary<string, GameObject> _lookup;

        public GameObject Find(string itemId)
        {
            if (_lookup == null || _lookup.Count != items.Count)
            {
                _lookup = new Dictionary<string, GameObject>(StringComparer.OrdinalIgnoreCase);
                foreach (var entry in items)
                {
                    _lookup[entry.itemId] = entry.model;
                }
            }
            return itemId != null && _lookup.TryGetValue(itemId, out var model) ? model : null;
        }
    }
}
