using System;
using System.Collections.Generic;
using UnityEngine;

namespace Reconnect.Client.Rooms
{
    /// <summary>
    /// Maps the ItemId stored in a room layout to a 3D model. Generated by ProjectSetup from
    /// Assets/ThirdParty/Kenney/Furniture (ItemId = file name, e.g. "loungeSofa") and
    /// Assets/ThirdParty/PolyHaven (ItemId = "ph-" + model name, e.g. "ph-sofa_02", real-world metres).
    /// Asset: Assets/_Project/Settings/ItemCatalog.asset.
    /// </summary>
    [CreateAssetMenu(menuName = "Reconnect/Item Catalog", fileName = "ItemCatalog")]
    public sealed class ItemCatalog : ScriptableObject
    {
        [Serializable]
        public sealed class Entry
        {
            public string itemId;
            public GameObject model;

            [Tooltip("0 = use the catalog's modelScale (Kenney); Poly Haven models are already in metres (1).")]
            public float scale;
        }

        [Tooltip("Kenney furniture uses 10 units per floor tile; our tiles are 1 m.")]
        public float modelScale = 0.1f;
        public List<Entry> items = new();

        private Dictionary<string, Entry> _lookup;

        public GameObject Find(string itemId) => FindEntry(itemId)?.model;

        /// <summary>Uniform scale that brings the model to real-life size.</summary>
        public float ScaleFor(string itemId) => FindEntry(itemId) is { scale: > 0f } entry ? entry.scale : modelScale;

        private Entry FindEntry(string itemId)
        {
            if (_lookup == null || _lookup.Count != items.Count)
            {
                _lookup = new Dictionary<string, Entry>(StringComparer.OrdinalIgnoreCase);
                foreach (var entry in items)
                {
                    _lookup[entry.itemId] = entry;
                }
            }
            return itemId != null && _lookup.TryGetValue(itemId, out var found) ? found : null;
        }
    }
}
