<Project Sdk="Microsoft.NET.Sdk">

  <!-- Building blocks for all modules: module contract, events, persistence helpers, web helpers. -->
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="EFCore.NamingConventions" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Reconnect.UnitTests" />
  </ItemGroup>

</Project>
